<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ISeedPlanningActivityIndicatorsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('planning_activity_indicators')->delete();

        \DB::table('planning_activity_indicators')->insert([
            0 => [
                'id' => 34,
                'planning_activity_version_id' => 47,
                'name' => 'Nilai Sakip Perangkat Daerah (Angka)',
                'baseline' => '45,6',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            1 => [
                'id' => 35,
                'planning_activity_version_id' => 49,
                'name' => 'Jumlah Orang yang Menerima Gaji dan Tunjangan ASN (Orang/bulan)',
                'baseline' => '88',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            2 => [
                'id' => 36,
                'planning_activity_version_id' => 51,
                'name' => 'Jumlah Orang yang Menerima Gaji dan Tunjangan ASN (Orang/bulan)',
                'baseline' => '88',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            3 => [
                'id' => 37,
                'planning_activity_version_id' => 53,
                'name' => 'Jumlah Paket Pakaian Dinas beserta Atribut Kelengkapan (Paket)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            4 => [
                'id' => 38,
                'planning_activity_version_id' => 55,
                'name' => 'Jumlah Paket Pakaian Dinas beserta Atribut Kelengkapan (Paket)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            5 => [
                'id' => 39,
                'planning_activity_version_id' => 57,
                'name' => 'Jumlah Paket Peralatan Rumah Tangga yang Disediakan (Paket)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            6 => [
                'id' => 40,
                'planning_activity_version_id' => 57,
                'name' => 'Jumlah Paket Peralatan dan Perlengkapan Kantor yang Disediakan (Paket)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            7 => [
                'id' => 41,
                'planning_activity_version_id' => 57,
                'name' => 'Jumlah Paket Komponen Instalasi Listrik/Penerangan Bangunan Kantor yang Disediakan (Paket)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            8 => [
                'id' => 42,
                'planning_activity_version_id' => 57,
                'name' => 'Jumlah Paket Barang Cetakan dan Penggandaan yang Disediakan (Paket)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            9 => [
                'id' => 43,
                'planning_activity_version_id' => 57,
                'name' => 'Jumlah Laporan Penyelenggaraan Rapat Koordinasi dan Konsultasi SKPD (Laporan)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            10 => [
                'id' => 44,
                'planning_activity_version_id' => 58,
                'name' => 'INDIKATOR OUTCOME / OUTPUT',
                'baseline' => 'BASELINE TAHUN 2024',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            11 => [
                'id' => 45,
                'planning_activity_version_id' => 59,
                'name' => '(02)',
                'baseline' => '(03)',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            12 => [
                'id' => 46,
                'planning_activity_version_id' => 61,
                'name' => 'Jumlah Paket Komponen Instalasi Listrik/Penerangan Bangunan Kantor yang Disediakan (Paket)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            13 => [
                'id' => 47,
                'planning_activity_version_id' => 63,
                'name' => 'Jumlah Paket Peralatan dan Perlengkapan Kantor yang Disediakan (Paket)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            14 => [
                'id' => 48,
                'planning_activity_version_id' => 65,
                'name' => 'Jumlah Paket Peralatan Rumah Tangga yang Disediakan (Paket)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            15 => [
                'id' => 49,
                'planning_activity_version_id' => 67,
                'name' => 'Jumlah Paket Barang Cetakan dan Penggandaan yang Disediakan (Paket)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            16 => [
                'id' => 50,
                'planning_activity_version_id' => 69,
                'name' => 'Jumlah Laporan Penyelenggaraan Rapat Koordinasi dan Konsultasi SKPD (Laporan)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            17 => [
                'id' => 51,
                'planning_activity_version_id' => 71,
                'name' => 'Jumlah Paket Mebel yang Disediakan (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            18 => [
                'id' => 52,
                'planning_activity_version_id' => 71,
                'name' => 'Jumlah Unit Kendaraan Dinas Operasional atau Lapangan yang Disediakan (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            19 => [
                'id' => 53,
                'planning_activity_version_id' => 71,
                'name' => 'Jumlah Unit Kendaraan Perorangan Dinas atau Kendaraan Dinas Jabatan yang Disediakan (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            20 => [
                'id' => 54,
                'planning_activity_version_id' => 71,
                'name' => 'Jumlah Unit Peralatan dan Mesin Lainnya yang Disediakan (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:04',
                'updated_at' => '2026-04-14 16:23:04',
            ],
            21 => [
                'id' => 55,
                'planning_activity_version_id' => 73,
                'name' => 'Jumlah Unit Kendaraan Perorangan Dinas atau Kendaraan Dinas Jabatan yang Disediakan (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            22 => [
                'id' => 56,
                'planning_activity_version_id' => 75,
                'name' => 'Jumlah Unit Kendaraan Dinas Operasional atau Lapangan yang Disediakan (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            23 => [
                'id' => 57,
                'planning_activity_version_id' => 77,
                'name' => 'Jumlah Paket Mebel yang Disediakan (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            24 => [
                'id' => 58,
                'planning_activity_version_id' => 78,
                'name' => 'INDIKATOR OUTCOME / OUTPUT',
                'baseline' => 'BASELINE TAHUN 2024',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            25 => [
                'id' => 59,
                'planning_activity_version_id' => 79,
                'name' => '(02)',
                'baseline' => '(03)',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            26 => [
                'id' => 60,
                'planning_activity_version_id' => 81,
                'name' => 'Jumlah Unit Peralatan dan Mesin Lainnya yang Disediakan (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            27 => [
                'id' => 61,
                'planning_activity_version_id' => 83,
                'name' => 'Jumlah Laporan Penyediaan Jasa Komunikasi, Sumber Daya Air dan Listrik yang Disediakan (Laporan)',
                'baseline' => '2',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            28 => [
                'id' => 62,
                'planning_activity_version_id' => 83,
                'name' => 'Jumlah Laporan Penyediaan Jasa Pelayanan Umum Kantor yang Disediakan (Laporan)',
                'baseline' => '1',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            29 => [
                'id' => 63,
                'planning_activity_version_id' => 85,
                'name' => 'Jumlah Laporan Penyediaan Jasa Komunikasi, Sumber Daya Air dan Listrik yang Disediakan (Laporan)',
                'baseline' => '2',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            30 => [
                'id' => 64,
                'planning_activity_version_id' => 87,
                'name' => 'Jumlah Laporan Penyediaan Jasa Pelayanan Umum Kantor yang Disediakan (Laporan)',
                'baseline' => '1',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            31 => [
                'id' => 65,
                'planning_activity_version_id' => 89,
                'name' => 'Jumlah Kendaraan Perorangan Dinas atau Kendaraan Dinas Jabatan yang Dipelihara dan dibayarkan Pajaknya (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            32 => [
                'id' => 66,
                'planning_activity_version_id' => 89,
                'name' => 'Jumlah Peralatan dan Mesin Lainnya yang Dipelihara  (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            33 => [
                'id' => 67,
                'planning_activity_version_id' => 89,
                'name' => 'Jumlah Sarana dan Prasarana Gedung Kantor atau Bangunan Lainnya yang Dipelihara/Direhabilitasi (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            34 => [
                'id' => 68,
                'planning_activity_version_id' => 89,
                'name' => 'Jumlah Kendaraan Dinas Operasional atau Lapangan yang Dipelihara dan dibayarkan Pajak dan Perizinannya (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            35 => [
                'id' => 69,
                'planning_activity_version_id' => 91,
                'name' => 'Jumlah Kendaraan Perorangan Dinas atau Kendaraan Dinas Jabatan yang Dipelihara dan dibayarkan Pajaknya (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            36 => [
                'id' => 70,
                'planning_activity_version_id' => 93,
                'name' => 'Jumlah Kendaraan Dinas Operasional atau Lapangan yang Dipelihara dan dibayarkan Pajak dan Perizinannya (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            37 => [
                'id' => 71,
                'planning_activity_version_id' => 95,
                'name' => 'INDIKATOR OUTCOME / OUTPUT',
                'baseline' => 'BASELINE TAHUN 2024',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            38 => [
                'id' => 72,
                'planning_activity_version_id' => 96,
                'name' => '(02)',
                'baseline' => '(03)',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            39 => [
                'id' => 73,
                'planning_activity_version_id' => 97,
                'name' => 'Jumlah Peralatan dan Mesin Lainnya yang Dipelihara  (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            40 => [
                'id' => 74,
                'planning_activity_version_id' => 99,
                'name' => 'Jumlah Sarana dan Prasarana Gedung Kantor atau Bangunan Lainnya yang Dipelihara/Direhabilitasi (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            41 => [
                'id' => 75,
                'planning_activity_version_id' => 101,
                'name' => 'Jumlah BLUD yang Menyediakan Pelayanan dan Penunjang Pelayanan (Unit Kerja)',
                'baseline' => '1',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            42 => [
                'id' => 76,
                'planning_activity_version_id' => 103,
                'name' => 'Jumlah BLUD yang Menyediakan Pelayanan dan Penunjang Pelayanan (Unit Kerja)',
                'baseline' => '1',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            43 => [
                'id' => 77,
                'planning_activity_version_id' => 105,
                'name' => 'Nilai Indeks Kepuasan Masyarakat (Angka)',
                'baseline' => '86',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            44 => [
                'id' => 78,
                'planning_activity_version_id' => 107,
                'name' => 'Jumlah Rumah sakit yang ditingkatkan  sarana, prasarana, alat kesehatan  dan SDM agar sesuai standar jenis pelayanan rumah sakit berdasarkan kelas rumah sakit yang memenuhi rasio tempat tidur terhadap jumlah penduduk minimal 1:1000 dan/atau dalam rangka peningkatan kapasitas pelayanan rumah sakit (Unit)',
                'baseline' => '1',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            45 => [
                'id' => 79,
                'planning_activity_version_id' => 107,
                'name' => 'Jumlah Sarana, Prasarana dan Alat Kesehatan yang Telah Dilakukan Program Rehabilitasi dan Pemeliharaan Oleh Rumah Sakit (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            46 => [
                'id' => 80,
                'planning_activity_version_id' => 107,
                'name' => 'Jumlah Obat, Bahan Habis Pakai, Bahan Medis Habis Pakai, Vaksin, Makanan dan Minuman di Fasilitas Kesehatan  yang disediakan (Paket)',
                'baseline' => '2',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            47 => [
                'id' => 81,
                'planning_activity_version_id' => 107,
                'name' => 'Jumlah Alat Kesehatan/Alat Penunjang Medik Fasilitas Pelayanan Kesehatan yang Disediakan (Unit)',
                'baseline' => '15',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            48 => [
                'id' => 82,
                'planning_activity_version_id' => 107,
                'name' => 'Jumlah Alat Kesehatan/Alat Penunjang Medik Fasilitas Layanan Kesehatan yang Terpelihara Sesuai Standar (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            49 => [
                'id' => 83,
                'planning_activity_version_id' => 108,
                'name' => 'INDIKATOR OUTCOME / OUTPUT',
                'baseline' => 'BASELINE TAHUN 2024',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            50 => [
                'id' => 84,
                'planning_activity_version_id' => 109,
                'name' => '(02)',
                'baseline' => '(03)',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            51 => [
                'id' => 85,
                'planning_activity_version_id' => 111,
                'name' => 'Jumlah Sarana, Prasarana dan Alat Kesehatan yang Telah Dilakukan Program Rehabilitasi dan Pemeliharaan Oleh Rumah Sakit (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            52 => [
                'id' => 86,
                'planning_activity_version_id' => 113,
                'name' => 'Jumlah Alat Kesehatan/Alat Penunjang Medik Fasilitas Pelayanan Kesehatan yang Disediakan (Unit)',
                'baseline' => '15',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            53 => [
                'id' => 87,
                'planning_activity_version_id' => 115,
                'name' => 'Jumlah Alat Kesehatan/Alat Penunjang Medik Fasilitas Layanan Kesehatan yang Terpelihara Sesuai Standar (Unit)',
                'baseline' => '-',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
            54 => [
                'id' => 88,
                'planning_activity_version_id' => 117,
                'name' => 'Jumlah Rumah sakit yang ditingkatkan  sarana, prasarana, alat kesehatan  dan SDM agar sesuai standar jenis pelayanan rumah sakit berdasarkan kelas rumah sakit yang memenuhi rasio tempat tidur terhadap jumlah penduduk minimal 1:1000 dan/atau dalam rangka peningkatan kapasitas pelayanan rumah sakit (Unit)',
                'baseline' => '1',
                'unit' => null,
                'created_at' => '2026-04-14 16:23:05',
                'updated_at' => '2026-04-14 16:23:05',
            ],
        ]);

    }
}
